server:
  port: 13000
spring:
  cloud:
    nacos:
      discovery:
        service: skill-serv
      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/skill?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379