server:
  port: 14000
spring:
  cloud:
    nacos:
      discovery:
        service: Ad-Serv
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/skill?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
canal:
  server: localhost:1111
  destination: example